### ISSUE TITLE
是这边嘛，为什么最后一步这个修改上传的弄不了，显示这样

### ISSUE THREAD

**Issue by FJ-FTH** [QZHY-HTX/Android-Application-Develop#2]
![mmexport1709806544450](https://github.com/QZHY-HTX/Android-Application-Develop/assets/161728347/906fac85-691f-4525-aefa-a1169c2d596d)

**Comment by QZHY-HTX** [comment]
Good Qusetion. 这里点击“始终”即可，后面还有个 Don't show again 类似的按钮也要点击一次。

平时分 + 1
